// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// AuthHandler is an autogenerated mock type for the AuthHandler type
type AuthHandler struct {
	mock.Mock
}

// Authorization provides a mock function with given fields: pCtx
func (_m *AuthHandler) Authorization(pCtx context.Context) gin.HandlerFunc {
	ret := _m.Called(pCtx)

	if len(ret) == 0 {
		panic("no return value specified for Authorization")
	}

	var r0 gin.HandlerFunc
	if rf, ok := ret.Get(0).(func(context.Context) gin.HandlerFunc); ok {
		r0 = rf(pCtx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}

	return r0
}

// UpdateAccessToken provides a mock function with given fields: pCtx
func (_m *AuthHandler) UpdateAccessToken(pCtx context.Context) gin.HandlerFunc {
	ret := _m.Called(pCtx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccessToken")
	}

	var r0 gin.HandlerFunc
	if rf, ok := ret.Get(0).(func(context.Context) gin.HandlerFunc); ok {
		r0 = rf(pCtx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}

	return r0
}

// NewAuthHandler creates a new instance of AuthHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthHandler {
	mock := &AuthHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
