// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/ummuys/reportify/internal/models"
)

// MetadataService is an autogenerated mock type for the MetadataService type
type MetadataService struct {
	mock.Mock
}

// GetCacheQueries provides a mock function with given fields: pCtx, key
func (_m *MetadataService) GetCacheQueries(pCtx context.Context, key string) ([]string, error) {
	ret := _m.Called(pCtx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetCacheQueries")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(pCtx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(pCtx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(pCtx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetColumns provides a mock function with given fields: pCtx, schemaName, tableName
func (_m *MetadataService) GetColumns(pCtx context.Context, schemaName string, tableName string) (*models.ListColumns, error) {
	ret := _m.Called(pCtx, schemaName, tableName)

	if len(ret) == 0 {
		panic("no return value specified for GetColumns")
	}

	var r0 *models.ListColumns
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.ListColumns, error)); ok {
		return rf(pCtx, schemaName, tableName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.ListColumns); ok {
		r0 = rf(pCtx, schemaName, tableName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ListColumns)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(pCtx, schemaName, tableName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSchemas provides a mock function with given fields: pCtx
func (_m *MetadataService) GetSchemas(pCtx context.Context) (*models.ListSchemas, error) {
	ret := _m.Called(pCtx)

	if len(ret) == 0 {
		panic("no return value specified for GetSchemas")
	}

	var r0 *models.ListSchemas
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*models.ListSchemas, error)); ok {
		return rf(pCtx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *models.ListSchemas); ok {
		r0 = rf(pCtx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ListSchemas)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(pCtx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTables provides a mock function with given fields: pCtx, schemaName
func (_m *MetadataService) GetTables(pCtx context.Context, schemaName string) (*models.ListTables, error) {
	ret := _m.Called(pCtx, schemaName)

	if len(ret) == 0 {
		panic("no return value specified for GetTables")
	}

	var r0 *models.ListTables
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.ListTables, error)); ok {
		return rf(pCtx, schemaName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.ListTables); ok {
		r0 = rf(pCtx, schemaName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ListTables)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(pCtx, schemaName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMetadataService creates a new instance of MetadataService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetadataService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetadataService {
	mock := &MetadataService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
