// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// MetadataHandler is an autogenerated mock type for the MetadataHandler type
type MetadataHandler struct {
	mock.Mock
}

// GetCacheQueries provides a mock function with given fields: pCtx
func (_m *MetadataHandler) GetCacheQueries(pCtx context.Context) gin.HandlerFunc {
	ret := _m.Called(pCtx)

	if len(ret) == 0 {
		panic("no return value specified for GetCacheQueries")
	}

	var r0 gin.HandlerFunc
	if rf, ok := ret.Get(0).(func(context.Context) gin.HandlerFunc); ok {
		r0 = rf(pCtx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}

	return r0
}

// GetColumns provides a mock function with given fields: pCtx
func (_m *MetadataHandler) GetColumns(pCtx context.Context) gin.HandlerFunc {
	ret := _m.Called(pCtx)

	if len(ret) == 0 {
		panic("no return value specified for GetColumns")
	}

	var r0 gin.HandlerFunc
	if rf, ok := ret.Get(0).(func(context.Context) gin.HandlerFunc); ok {
		r0 = rf(pCtx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}

	return r0
}

// GetSchemas provides a mock function with given fields: pCtx
func (_m *MetadataHandler) GetSchemas(pCtx context.Context) gin.HandlerFunc {
	ret := _m.Called(pCtx)

	if len(ret) == 0 {
		panic("no return value specified for GetSchemas")
	}

	var r0 gin.HandlerFunc
	if rf, ok := ret.Get(0).(func(context.Context) gin.HandlerFunc); ok {
		r0 = rf(pCtx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}

	return r0
}

// GetTables provides a mock function with given fields: pCtx
func (_m *MetadataHandler) GetTables(pCtx context.Context) gin.HandlerFunc {
	ret := _m.Called(pCtx)

	if len(ret) == 0 {
		panic("no return value specified for GetTables")
	}

	var r0 gin.HandlerFunc
	if rf, ok := ret.Get(0).(func(context.Context) gin.HandlerFunc); ok {
		r0 = rf(pCtx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}

	return r0
}

// NewMetadataHandler creates a new instance of MetadataHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetadataHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetadataHandler {
	mock := &MetadataHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
