// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	os "os"

	mock "github.com/stretchr/testify/mock"
)

// ReportConvert is an autogenerated mock type for the ReportConvert type
type ReportConvert struct {
	mock.Mock
}

// ToPDF provides a mock function with given fields: headers, data, f
func (_m *ReportConvert) ToPDF(headers []string, data [][]interface{}, f *os.File) error {
	ret := _m.Called(headers, data, f)

	if len(ret) == 0 {
		panic("no return value specified for ToPDF")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]string, [][]interface{}, *os.File) error); ok {
		r0 = rf(headers, data, f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewReportConvert creates a new instance of ReportConvert. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportConvert(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportConvert {
	mock := &ReportConvert{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
