// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ReportCache is an autogenerated mock type for the ReportCache type
type ReportCache struct {
	mock.Mock
}

// GetCacheQueries provides a mock function with given fields: pCtx
func (_m *ReportCache) GetCacheQueries(pCtx context.Context) (map[string][]string, error) {
	ret := _m.Called(pCtx)

	if len(ret) == 0 {
		panic("no return value specified for GetCacheQueries")
	}

	var r0 map[string][]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string][]string, error)); ok {
		return rf(pCtx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string][]string); ok {
		r0 = rf(pCtx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(pCtx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetQueries provides a mock function with given fields: pCtx, key
func (_m *ReportCache) GetQueries(pCtx context.Context, key string) ([]string, error) {
	ret := _m.Called(pCtx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetQueries")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(pCtx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(pCtx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(pCtx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetQuery provides a mock function with given fields: pCtx, key, value
func (_m *ReportCache) SetQuery(pCtx context.Context, key string, value interface{}) error {
	ret := _m.Called(pCtx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for SetQuery")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(pCtx, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WarmUp provides a mock function with given fields: pCtx, queries
func (_m *ReportCache) WarmUp(pCtx context.Context, queries map[string][]string) error {
	ret := _m.Called(pCtx, queries)

	if len(ret) == 0 {
		panic("no return value specified for WarmUp")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string][]string) error); ok {
		r0 = rf(pCtx, queries)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewReportCache creates a new instance of ReportCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportCache {
	mock := &ReportCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
