// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// ReportHandler is an autogenerated mock type for the ReportHandler type
type ReportHandler struct {
	mock.Mock
}

// CreateReport provides a mock function with given fields: pCtx
func (_m *ReportHandler) CreateReport(pCtx context.Context) gin.HandlerFunc {
	ret := _m.Called(pCtx)

	if len(ret) == 0 {
		panic("no return value specified for CreateReport")
	}

	var r0 gin.HandlerFunc
	if rf, ok := ret.Get(0).(func(context.Context) gin.HandlerFunc); ok {
		r0 = rf(pCtx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}

	return r0
}

// NewReportHandler creates a new instance of ReportHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportHandler {
	mock := &ReportHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
