// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	os "os"

	mock "github.com/stretchr/testify/mock"
)

// ReportService is an autogenerated mock type for the ReportService type
type ReportService struct {
	mock.Mock
}

// CreateReport provides a mock function with given fields: pCtx, user_id, sql, f
func (_m *ReportService) CreateReport(pCtx context.Context, user_id int64, sql string, f *os.File) error {
	ret := _m.Called(pCtx, user_id, sql, f)

	if len(ret) == 0 {
		panic("no return value specified for CreateReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, *os.File) error); ok {
		r0 = rf(pCtx, user_id, sql, f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewReportService creates a new instance of ReportService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportService {
	mock := &ReportService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
