// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ReportDB is an autogenerated mock type for the ReportDB type
type ReportDB struct {
	mock.Mock
}

// ExecQuery provides a mock function with given fields: pCtx, script
func (_m *ReportDB) ExecQuery(pCtx context.Context, script string) ([]string, [][]interface{}, error) {
	ret := _m.Called(pCtx, script)

	if len(ret) == 0 {
		panic("no return value specified for ExecQuery")
	}

	var r0 []string
	var r1 [][]interface{}
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, [][]interface{}, error)); ok {
		return rf(pCtx, script)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(pCtx, script)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) [][]interface{}); ok {
		r1 = rf(pCtx, script)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([][]interface{})
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(pCtx, script)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetColumns provides a mock function with given fields: pCtx, schemaName, tableName
func (_m *ReportDB) GetColumns(pCtx context.Context, schemaName string, tableName string) (map[string]string, error) {
	ret := _m.Called(pCtx, schemaName, tableName)

	if len(ret) == 0 {
		panic("no return value specified for GetColumns")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (map[string]string, error)); ok {
		return rf(pCtx, schemaName, tableName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) map[string]string); ok {
		r0 = rf(pCtx, schemaName, tableName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(pCtx, schemaName, tableName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSchemas provides a mock function with given fields: pCtx
func (_m *ReportDB) GetSchemas(pCtx context.Context) (map[string]string, error) {
	ret := _m.Called(pCtx)

	if len(ret) == 0 {
		panic("no return value specified for GetSchemas")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]string, error)); ok {
		return rf(pCtx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]string); ok {
		r0 = rf(pCtx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(pCtx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTables provides a mock function with given fields: pCtx, schemaName
func (_m *ReportDB) GetTables(pCtx context.Context, schemaName string) (map[string]string, error) {
	ret := _m.Called(pCtx, schemaName)

	if len(ret) == 0 {
		panic("no return value specified for GetTables")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return rf(pCtx, schemaName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = rf(pCtx, schemaName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(pCtx, schemaName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReportDB creates a new instance of ReportDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportDB {
	mock := &ReportDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
