// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserDB is an autogenerated mock type for the UserDB type
type UserDB struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: pCtx, username, hashPassword
func (_m *UserDB) CreateUser(pCtx context.Context, username string, hashPassword string) error {
	ret := _m.Called(pCtx, username, hashPassword)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(pCtx, username, hashPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: pCtx, username
func (_m *UserDB) Exists(pCtx context.Context, username string) error {
	ret := _m.Called(pCtx, username)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(pCtx, username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCacheQueries provides a mock function with given fields: pCtx
func (_m *UserDB) GetCacheQueries(pCtx context.Context) (map[string][]string, error) {
	ret := _m.Called(pCtx)

	if len(ret) == 0 {
		panic("no return value specified for GetCacheQueries")
	}

	var r0 map[string][]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string][]string, error)); ok {
		return rf(pCtx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string][]string); ok {
		r0 = rf(pCtx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(pCtx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPassword provides a mock function with given fields: pCtx, username
func (_m *UserDB) GetPassword(pCtx context.Context, username string) (int64, string, error) {
	ret := _m.Called(pCtx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetPassword")
	}

	var r0 int64
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, string, error)); ok {
		return rf(pCtx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(pCtx, username)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(pCtx, username)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(pCtx, username)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SetCacheQueries provides a mock function with given fields: pCtx, cache
func (_m *UserDB) SetCacheQueries(pCtx context.Context, cache map[string][]string) error {
	ret := _m.Called(pCtx, cache)

	if len(ret) == 0 {
		panic("no return value specified for SetCacheQueries")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string][]string) error); ok {
		r0 = rf(pCtx, cache)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserDB creates a new instance of UserDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserDB {
	mock := &UserDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
